import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { parse } from 'yaml';

const rootDir = resolve(import.meta.dirname, '..');
const inputPath = resolve(rootDir, 'openapi/openapi.yaml');
const outputPath = resolve(rootDir, 'src/generated/openapi.ts');

type JsonObject = Record<string, unknown>;

const sortDeep = (value: unknown): unknown => {
  if (Array.isArray(value)) {
    return value.map((item) => sortDeep(item));
  }

  if (value && typeof value === 'object') {
    return Object.keys(value as JsonObject)
      .sort()
      .reduce<JsonObject>((acc, key) => {
        acc[key] = sortDeep((value as JsonObject)[key]);
        return acc;
      }, {});
  }

  return value;
};

const toMethodMap = (document: JsonObject): Record<string, string[]> => {
  const paths = (document.paths ?? {}) as Record<string, Record<string, unknown>>;
  return Object.keys(paths)
    .sort()
    .reduce<Record<string, string[]>>((acc, path) => {
      const methods = Object.keys(paths[path] ?? {})
        .filter((method) => ['get', 'post', 'put', 'patch', 'delete', 'options', 'head'].includes(method.toLowerCase()))
        .map((method) => method.toLowerCase())
        .sort();
      acc[path] = methods;
      return acc;
    }, {});
};

const buildOutput = (document: JsonObject): string => {
  const sortedDocument = sortDeep(document);
  const pathMethodMap = toMethodMap(document);
  const pathLiterals = Object.keys(pathMethodMap).map((path) => `'${path}'`).join(' | ') || 'never';
  const methodMapSource = Object.entries(pathMethodMap)
    .map(([path, methods]) => `  '${path}': [${methods.map((method) => `'${method}'`).join(', ')}],`)
    .join('\n');

  return [
    '// Auto-generated by packages/shared/scripts/generate-openapi-types.ts',
    '// Source: packages/shared/openapi/openapi.yaml',
    '',
    `export const openApiDocument = ${JSON.stringify(sortedDocument, null, 2)} as const;`,
    '',
    `export type OpenApiPath = ${pathLiterals};`,
    '',
    'export const openApiPathMethodMap = {',
    methodMapSource,
    '} as const;'
  ].join('\n');
};

const main = async () => {
  const input = await readFile(inputPath, 'utf8');
  const parsed = parse(input) as JsonObject;
  const output = buildOutput(parsed);

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output + '\n', 'utf8');
};

await main();
